content/urls.py
from django.conf.urls import patterns, url
from content import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^browse/$', views.browse, name='browse'),	
	url(r'^browse/(?P<browse_by>[A-Za-z]+)/$', views.browse_by, name='browse_by'),
	url(r'^search/(?P<search_by>[A-Za-z]+)/$', views.search, name='search'),
	url(r'^comic/(?P<series>[A-Za-z ()0-9:]+)/(?P<issue>[0-9]+)/$', views.comic, name='comic'),
	url(r'^review/(?P<series>[A-Za-z ()0-9:]+)/(?P<issue>[0-9]+)/(?P<id>[-0-9]+)/$', views.review, name='review'),
	url(r'^login/$', views.login_view, name='login'),
	url(r'^login/e=(?P<error>[0-9])&m=(?P<message>[0-9])/$', views.login_view, name='login'),
	url(r'^register/$', views.register, name='register'),
	url(r'^register/e=(?P<error>[0-9])$', views.register, name='register'),
	url(r'^account_request/(?P<type>[A-Za-z]+)/$', views.account_request, name='account_request'),
	url(r'^review/(?P<series>[A-Za-z ()0-9:]+)/(?P<issue>[0-9]+)/(?P<action>[A-Za-z]+)/$', views.ownership, name='ownership'),
	url(r'^collection/$', views.collection, name='collection'),	
	url(r'^collection/(?P<listing>[A-Za-z]+)/$', views.collection_other, name='collection_other'),
	url(r'^rating/(?P<series>[A-Za-z ()0-9:]+)/(?P<issue>[0-9]+)/$', views.rating, name='rating'),
	url(r'^reading/$', views.reading, name='reading'),
)

new52collect/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'new52collect.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^content/', include('content.urls', namespace='content')),
    url(r'^admin/', include(admin.site.urls)),
)

content/models.py
from django.db import models

# Create your models here.

class Character(models.Model):
	name = models.TextField()

	def __unicode__(self):
		return self.name

class Comic(models.Model):
	series = models.TextField()
	issue_num = models.IntegerField()
	title = models.TextField()
	writer = models.TextField()
	penciller = models.TextField()
	cover = models.TextField(null = True)
	rating = models.FloatField()
	characters = models.ManyToManyField(Character)
	cover_price = models.FloatField()

	def __unicode__(self):
		return self.series + " #" + str(self.issue_num)

class Review(models.Model):
	comic = models.ForeignKey(Comic)
	author = models.TextField()
	content = models.TextField()
	date = models.DateField()

class Owns(models.Model):
	user = models.TextField()
	comic = models.ForeignKey(Comic)
	read = models.BooleanField(default = False)
	wish = models.BooleanField(default = False)
	rating = models.IntegerField(null = True)
	priority = models.IntegerField(null = True)

content/views.py
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render
from content.models import Comic, Character, Review, Owns
import datetime
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

# Create your views here.

# homepage
def index(request):
	context = {
	}
	return render(request, 'content/index.html', context)

# default browse page, no category selected
def browse(request):
	context = {
	}
	return render(request, 'content/browse.html', context)

# browse page, category selected
def browse_by(request, browse_by):
	series_list = None
	if browse_by == "series":
		series_list = Comic.objects.all().order_by('series').values_list('series', flat=True).distinct()
		series_list = map(lambda x:(x, Comic.objects.filter(series=x).order_by('issue_num')), series_list)
	elif browse_by == "character":
		series_list = Character.objects.all().order_by('name').values_list('name', flat=True).distinct()
		series_list = map(lambda x:(x, Comic.objects.filter(characters__name=x).order_by('series')), series_list)
	elif browse_by == "writer":
		series_list = Comic.objects.all().order_by('writer').values_list('writer', flat=True).distinct()
		series_list = map(lambda x:(x, Comic.objects.filter(writer=x).order_by('series')), series_list)
	elif browse_by == "artist":
		series_list = Comic.objects.all().order_by('penciller').values_list('penciller', flat=True).distinct()
		series_list = map(lambda x:(x, Comic.objects.filter(penciller=x).order_by('series')), series_list)
	context = {
		'browse_by': browse_by,
		'series_list': series_list,
	}
	return render(request, 'content/browse.html', context)

# handles search queries
def search(request, search_by):
	if search_by == 'series':
		series_list = Comic.objects.filter(series__icontains=request.POST['content']).order_by('series').values_list('series', flat=True).distinct()
		series_list = map(lambda x:(x, Comic.objects.filter(series=x).order_by('issue_num')), series_list)
	elif search_by == 'character':
		series_list = Character.objects.filter(name__icontains=request.POST['content']).order_by('name').values_list('name', flat=True).distinct()
		series_list = map(lambda x:(x, Comic.objects.filter(characters__name=x).order_by('series')), series_list)
	elif search_by == 'writer':
		series_list = Comic.objects.filter(writer__icontains=request.POST['content']).order_by('writer').values_list('writer', flat=True).distinct()
		series_list = map(lambda x:(x, Comic.objects.filter(writer=x).order_by('series')), series_list)
	elif search_by == 'artist':
		series_list = Comic.objects.filter(penciller__icontains=request.POST['content']).order_by('penciller').values_list('penciller', flat=True).distinct()
		series_list = map(lambda x:(x, Comic.objects.filter(penciller=x).order_by('series')), series_list)
	context = {
		'browse_by': search_by,
		'series_list': series_list,
	}
	return render(request, 'content/browse.html', context)

# displays information for specific comic book
def comic(request, series, issue):
	comic = Comic.objects.filter(series=series, issue_num=issue)[0]
	reviews = Review.objects.filter(comic_id=comic.id)
	ownership = Owns.objects.filter(user=request.user.username, comic=comic)
	if len(ownership) > 0:
		ownership = ownership[0]
		if ownership.wish:
			ownership = 'wish'
		else:
			ownership = 'owned'
		rating = Owns.objects.get(user=request.user.username, comic=comic).rating
	else:
		ownership = False
		rating = None
	ratings = Owns.objects.filter(comic=comic).values_list('rating', flat=True)
	ratings = [float(rating) for rating in ratings if rating is not None]
	if len(ratings) > 0:
		avg = sum(ratings) / len(ratings)
	else:
		avg = 0.0
	comic.rating = round(avg, 1);
	comic.save()
	context = {
		'comic': comic,
		'characters': comic.characters.all(),
		'review_list': reviews,
		'ownership': ownership,
		'rating': rating,
	}
	return render(request, 'content/comic.html', context)

# handles review submissions
def review(request, series, issue, id):
	if id == '-1':
		comic = Comic.objects.get(series=series, issue_num=issue)
		author = request.user.username
		review = Review(comic=comic, author=author, content=request.POST['content'], date=datetime.date.today())
		review.save()
		return HttpResponseRedirect(reverse('content:comic', args=(series, issue,)))
	else:
		review = Review.objects.get(id = id)
		review.delete();
		return HttpResponseRedirect(reverse('content:comic', args=(series, issue,)))

# login page
def login_view(request, error = 0, message = 0):
	context = {
		'error': error,
		'message': message,
	}
	return render(request, 'content/login.html', context)

# registration page
def register(request, error = 0):
	context = {
		'error': error,
	}
	return render(request, 'content/register.html', context)

# handles account operations (login, register, logout)
def account_request(request, type):
	if type == 'logout':
		logout(request)
		return HttpResponseRedirect(reverse('content:login', args=(0, 2,)))

	username = request.POST['username']
	password = request.POST['password']
	
	if type == 'login':
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				if('content/login' in request.META.get('HTTP_REFERER')):
					return HttpResponseRedirect("/content")
				else:
					return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
		return HttpResponseRedirect(reverse('content:login', args=(1, 0,)))
	elif type == 'register':
		user = User.objects.filter(username=username);
		if len(user) > 0:
			return HttpResponseRedirect(reverse('content:register', args=(1,)))
		elif password != request.POST['confirm']:
			return HttpResponseRedirect(reverse('content:register', args=(2,)))
		else:
			user = User.objects.create_user(username=username, password=password)
			user.save()
			return HttpResponseRedirect(reverse('content:login', args=(0, 1,)))

# handles changes in ownership status
def ownership(request, series, issue, action):
	comic = Comic.objects.get(series=series, issue_num=issue)
	ownership = Owns.objects.filter(user=request.user.username, comic=comic)
	if len(ownership) > 0:
		ownership = ownership[0]
		if action == 'add' and ownership.wish == True:
			ownership.wish = False
			ownership.save()
		elif action == 'remove':
			ownership.delete()
		elif action == 'toggleread':
			ownership.read = not ownership.read
			ownership.save()
		elif action == 'readingadd':
			ownership.priority = len(Owns.objects.filter(user=request.user.username, wish=False, read=False, priority__isnull=False)) + 1
			ownership.save()
		elif action == 'readingremove':
			next_items = Owns.objects.filter(priority__gt=ownership.priority)
			for item in next_items:
				item.priority -= 1
				item.save()
			ownership.priority = None
			ownership.save()
		elif action == 'readingtoggleread':
			next_items = Owns.objects.filter(priority__gt=ownership.priority)
			for item in next_items:
				item.priority -= 1
				item.save()
			ownership.read = not ownership.read
			ownership.priority = None
			ownership.save()
		elif action == 'incrementpriority':
			next_item = Owns.objects.get(priority=ownership.priority + 1)
			next_item.priority -= 1
			ownership.priority += 1
			next_item.save()
			ownership.save()
		elif action == 'decrementpriority':
			prev_item = Owns.objects.get(priority=ownership.priority - 1)
			prev_item.priority += 1
			ownership.priority -= 1
			prev_item.save()
			ownership.save()
	else:
		if action == 'add':
			add = Owns(user=request.user.username, comic=comic, wish=False)
		elif action == 'wish':
			add = Owns(user=request.user.username, comic=comic, wish=True)
		add.save()
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

# collection page
def collection(request):
	collection = Owns.objects.filter(user=request.user.username, wish=False)
	collection = map(lambda x:x.comic.id, collection)
	series_list = Comic.objects.filter(id__in=collection).order_by('series').values_list('series', flat=True).distinct()
	series_list = map(lambda x:[x, Comic.objects.filter(series=x, id__in=collection).order_by('issue_num')], series_list)
	for series in series_list:
		series[1] = map(lambda x:[x, Owns.objects.get(user=request.user.username, comic=x).read, Owns.objects.get(user=request.user.username, comic=x).priority], series[1])
	context = {
		'series_list': series_list
	}
	return render(request, 'content/collection.html', context)

# other lists is collection page (e.g. wishlist)
def collection_other(request, listing):
	series_list = None
	if listing == "wishlist":
		collection = Owns.objects.filter(user=request.user.username, wish=True)
		collection = map(lambda x:x.comic.id, collection)
		series_list = Comic.objects.filter(id__in=collection).order_by('series').values_list('series', flat=True).distinct()
		series_list = map(lambda x:[x, Comic.objects.filter(series=x, id__in=collection).order_by('issue_num')], series_list)
		read = False
	elif listing == "incomplete":
		collection = Owns.objects.filter(user=request.user.username, wish=False)
		collection = map(lambda x:x.comic.id, collection)
		series_list = Comic.objects.filter(id__in=collection).order_by('series').values_list('series', flat=True).distinct()
		series_list = map(lambda x:[x, Comic.objects.filter(series=x).exclude(id__in=collection).order_by('issue_num')], series_list)
		read = False
	elif listing == "read":
		collection = Owns.objects.filter(user=request.user.username, read=True)
		collection = map(lambda x:x.comic.id, collection)
		series_list = Comic.objects.filter(id__in=collection).order_by('series').values_list('series', flat=True).distinct()
		series_list = map(lambda x:[x, Comic.objects.filter(series=x, id__in=collection).order_by('issue_num')], series_list)
		read = True
	elif listing == "unread":
		collection = Owns.objects.filter(user=request.user.username, read=False)
		collection = map(lambda x:x.comic.id, collection)

content/templates/content/comic.html
<html>
<head>
<title>The New 52 Collector</title>

{% load staticfiles %}

<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"> -->
<link rel="stylesheet" type="text/css" href="{% static 'content/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'content/blog.css' %}" />
</head>
<body>
<nav class="navbar navbar-inverse navbar-static-top">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" href="/content/">New 52 Collector</a>
		</div>
		<div>
			<ul class="nav navbar-nav">
				<li><a href="/content/browse">Browse</a></li>
				{% if user.is_authenticated %}
				<li><a href="/content/collection">Collection</a></li>
				<li><a href="/content/reading">Reading List</a></li>
				{% else %}
				<li><a href="/content/login">Collection</a></li>
				<li><a href="/content/login">Reading List</a></li>
				{% endif %}
			</ul>
		</div>
		{% if user.is_authenticated %}
		<form class="navbar-form navbar-right" action="{% url 'content:account_request' 'logout' %}">
	        <button type="submit" class="btn btn-danger">Logout</button>
	    </form>
		{% else %}
		<form class="navbar-form navbar-right" style="padding-left: 0px" action="/content/register">
		    <button type="submit" class="btn btn-success">Sign Up</button>
		</form>
		<form class="navbar-form navbar-right" style="padding-right: 10px" action="{% url 'content:account_request' 'login' %}" method="post">
			{% csrf_token %}
	        <div class="form-group">
	           	<input type="text" placeholder="username" name="username" class="form-control">
	        </div>
	        <div class="form-group">
	            <input type="password" placeholder="password" name="password" class="form-control">
	        </div>
	        <button type="submit" class="btn btn-primary">Login</button>
	    </form>
	    {% endif %}
	</div>
</nav>
<div class="container">
	{% if comic %}
	{% endif %}
	<!-- <div class="blog-header">
		<h1 class="blog-title">{{ comic.series }} #{{ comic.issue_num }}</h1>
		<p class="lead blog-description">{{ comic.title }}</p>
	</div> -->
	<div class="row">
		<div class="col-sm-8 blog-main">
			<div class="blog-post">
				<h2 class="blog-post-title">{{ comic.series }} #{{ comic.issue_num }}</h2>
            	<p class="blog-post-meta">{{ comic.title }}</p>
            	<hr>
            	{% if comic.cover %}
				<img src="{% static 'images/' %}{{ comic.cover }}" style="display: inline-block; width: 50%"/>
				{% endif %}
				<div style="display: inline-block; float: right; width: 41%">
					<h3>Writer</h3>
	            	<p>{{ comic.writer }}</p>
	            	<h3>Penciller</h3>
	            	<p>{{ comic.penciller }}</p>
	            	<hr>
	            	<div style="padding-top: 50px;">
	            	{% if user.is_authenticated %}
	            		{% if ownership == 'owned' %}
	            			<form style="display: inline-block" action="{% url 'content:ownership' comic.series comic.issue_num 'remove' %}" method="post">
		            		{% csrf_token %}
					        <button type="submit" class="btn btn-danger">remove from collection</button>
					    </form>
	            		{% else %}
		            	<form style="display: inline-block" action="{% url 'content:ownership' comic.series comic.issue_num 'add' %}" method="post">
		            		{% csrf_token %}
					        <button type="submit" class="btn btn-primary">add to collection</button>
					    </form>
					    	{% if ownership == 'wish' %}
					    	<form style="display: inline-block" action="{% url 'content:ownership' comic.series comic.issue_num 'remove' %}" method="post">
						    	{% csrf_token %}
						        <button type="submit" class="btn btn-danger">remove from wishlist</button>
						    </form>
					    	{% else %}
						    <form style="display: inline-block" action="{% url 'content:ownership' comic.series comic.issue_num 'wish' %}" method="post">
						    	{% csrf_token %}
						        <button type="submit" class="btn btn-success">add to wishlist</button>
						    </form>
							{% endif %}
						{% endif %}
					{% else %}
					<form action="{% url 'content:login' %}" style="margin: 0; color: #999">
						<input type="submit" value="login to manage collection" style="border: none; background: none"/>
					</form>
					{% endif %}
					</div>
	            </div>
			</div>
			<div class="blog-post">
				<h2>Reviews</h2>
				<hr>
				<ul class="media-list">
				{% for review in review_list %}
					<li class="media">
						<div class="media-body" style="display:inline-block; width: 90%">
							<h4 class="media-heading" style="font-weight: bold">{{ review.author }}</h4>
							<h5 class="media-heading" style="color: #999">{{ review.date }}</h5>
							<p style="font-size: 15">{{ review.content }}</p>
							
						</div>
						{% if user.username == review.author %}
						<form action="{% url 'content:review' comic.series comic.issue_num review.id %}" method="post" style="display: inline-block; padding-top: 15px">
							{% csrf_token %}
					        <button class="btn btn-default btn-sm" type="submit" name="submit-review">delete</button>
					    </form>
						{% endif %}
					</li>
				{% endfor %}
				</ul>
				<hr>
				{% if user.is_authenticated %}
					{% if ownership == "owned" %}
					<div style="border: 1px solid #bbb; margin: 50px">
						<h3 style="background: #2980b9; color: rgba(255,255,255,1); border-bottom:1px solid #bbb; padding:10px; text-align:center">New Review</h3>
						<form style="padding:10px" action="{% url 'content:review' comic.series comic.issue_num -1 %}" method="post">
							{% csrf_token %}
							<!-- <div class="form-group">
								<input class="form-control" id="review-name" type="text" name="author" placeholder="name">
							</div> -->
							<div class="form-group">
								<textarea class="form-control" id="review-content" type="text" name="content" placeholder="content"></textarea>
							</div>
							<button type="submit" id="submit-review" class="btn btn-default" name="submit-review" style="margin: 0 auto; display: block">Submit</button>
						</form>
					</div>
					{% else %}
					<div style="padding:10px; color: #999">
						<span style="display: block; text-align: center; padding: 10px	">must own to review</span>
					</div>
					{% endif %}
				{% else %}
				<div style="padding:10px; color: #999">
					<span style="display: block; text-align: center; padding: 10px	">login to add new review</span>
					<form action="/content/login">
				        <button type="submit" class="btn btn-primary" style="display:block ; margin: 0 auto">Login</button>
				    </form>
				</div>
				{% endif %}
			</div>
		</div><!-- /.blog-main -->
		<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
		  <div class="sidebar-module sidebar-module-inset" style="padding-left: 28%">
			<h4 style="padding-left: 20.5%">Rating</h4>
			<h1 style="padding-left: 21%;">{{ comic.rating }}</h1>
			{% if user.is_authenticated %}
				{% if ownership == "owned" %}
				<p style="color: #999">Your Rating: {{ rating }}</p>
				<form action="{% url 'content:rating' comic.series comic.issue_num %}" method="post">
					{% csrf_token %}
					<input class="form-control" style="display: inline-block; width: 40%" type="number" min="0" max="10" name="rating"/>
					<button type="submit" class="btn btn-success">Rate</button>
				</form>
				{% else %}
				<div style="color: #999; padding-left: 14%;padding-bottom: 10px">
					<span>own to rate</span>
				</div>
				{% endif %}
			{% else %}
			<form action="{% url 'content:login' %}" style="margin: 0; color: #999">
				<input type="submit" value="login to rate" style="border: none; background: none; padding-bottom: 10px"/>
			</form>
			{% endif %}
			<h4>Cover Price</h4>
			<p>${{ comic.cover_price }}</p>
		  </div>
		  <div class="sidebar-module">
			<h4>Characters</h4>
			<ol class="list-unstyled">
			{% for character in characters %}
				<li>
					<form id="form{{ forloop.counter }}" action="{% url 'content:search' 'character' %}" method="post" style="margin: 0; color: #999">
						{% csrf_token %}
						<input type="submit" name="content" value="{{ character.name }}" style="border: none; background: none"/>
					</form>
				</li>
			{% endfor %}
			</ol>
		</div>
		  <!-- <div class="sidebar-module">
			<h4>Archives</h4>
			<ol class="list-unstyled">
			  <li><a href="#">March 2014</a></li>
			  <li><a href="#">February 2014</a></li>
			  <li><a href="#">January 2014</a></li>
			  <li><a href="#">December 2013</a></li>
			  <li><a href="#">November 2013</a></li>
			  <li><a href="#">October 2013</a></li>
			  <li><a href="#">September 2013</a></li>
			  <li><a href="#">August 2013</a></li>
			  <li><a href="#">July 2013</a></li>
			  <li><a href="#">June 2013</a></li>
			  <li><a href="#">May 2013</a></li>
			  <li><a href="#">April 2013</a></li>
			</ol>
		  </div>
		  <div class="sidebar-module">
			<h4>Elsewhere</h4>
			<ol class="list-unstyled">
			  <li><a href="#">GitHub</a></li>
			  <li><a href="#">Twitter</a></li>
			  <li><a href="#">Facebook</a></li>
			</ol>
		  </div> -->
		</div><!-- /.blog-sidebar -->
	</div>
</div>
</body>

</html>

content/templates/content/reading.html
<html>
<head>
<title>The New 52 Collector</title>

{% load staticfiles %}

<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"> -->
<link rel="stylesheet" type="text/css" href="{% static 'content/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'content/dashboard.css' %}" />
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" href="/content/">New 52 Collector</a>
		</div>
		<div>
			<ul class="nav navbar-nav">
				<li><a href="/content/browse">Browse</a></li>
				{% if user.is_authenticated %}
				<li><a href="/content/collection">Collection</a></li>
				<li class="active"><a href="/content/reading">Reading List</a></li>
				{% else %}
				<li><a href="/content/login">Collection</a></li>
				<li><a href="/content/login">Reading List</a></li>
				{% endif %}
			</ul>
		</div>
		{% if user.is_authenticated %}
		<form class="navbar-form navbar-right" action="{% url 'content:account_request' 'logout' %}">
	        <button type="submit" class="btn btn-danger">Logout</button>
	    </form>
		{% else %}
		<form class="navbar-form navbar-right" style="padding-left: 0px" action="/content/register">
		    <button type="submit" class="btn btn-success">Sign Up</button>
		</form>
		<form class="navbar-form navbar-right" style="padding-right: 10px" action="{% url 'content:account_request' 'login' %}" method="post">
			{% csrf_token %}
	        <div class="form-group">
	           	<input type="text" placeholder="username" name="username" class="form-control">
	        </div>
	        <div class="form-group">
	            <input type="password" placeholder="password" name="password" class="form-control">
	        </div>
	        <button type="submit" class="btn btn-primary">Login</button>
	    </form>
	    {% endif %}
	</div>
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="main" style="width: 60%; margin: 0 auto">
<!-- <div id="page" class="container">
	<div>
		<div> -->
		<h1 class="page-header">Reading List</h1>
			<div class="list-group">
				<li id="exp{{forloop.counter}}" class="list-group-item active" style="text-align: left">
					<a href="#" class="list-group-item active" style="display: inline"></a>
				</li>
				<!-- <ul class="list-group"> -->
				{% for issue in reading_list %}
				<li class="list-group-item" style="text-align: left">
					<div style="display: inline-block;">
						{% if forloop.first %}
						<form style="display: block; margin: 0 5;" action="#">
						{% else %}
						<form style="display: block; margin: 0 5;" action="{% url 'content:ownership' issue.series issue.issue_num 'decrementpriority' %}" method="post">
						{% endif %}
		            	{% csrf_token %}
			        		<input type="image" src="{% static 'arrows/up-resized.png' %}" alt="up" height="15" width="15">
			        	</form>
			        	{% if forloop.counter == length %}
						<form style="display: block; margin: 0 5" action="#">
						{% else %}
						<form style="display: block; margin: 0 5" action="{% url 'content:ownership' issue.series issue.issue_num 'incrementpriority' %}" method="post">
						{% endif %}
		            	{% csrf_token %}
			        		<input type="image" src="{% static 'arrows/down-resized.png' %}" alt="down" height="15" width="15">
			        	</form>
					</div>
					<div style="display: inline-block; width: 80%; position: relative; top: 50%; transform: translateY(-40%);">
						<a href="/content/comic/{{issue.series}}/{{issue.issue_num}}">{{ issue.series }} #{{ issue.issue_num }} - {{ issue.title }}</a>
					</div>
					<form style="display: inline-block; height: 15px; position: relative; top: 50%; transform: translateY(-40%);" action="{% url 'content:ownership' issue.series issue.issue_num 'readingremove' %}" method="post">
		            	{% csrf_token %}
			        	<button type="submit" class="btn btn-danger btn-sm">remove</button>
			        </form>
			        <form style="display: inline-block; height: 15px; position: relative; top: 50%; transform: translateY(-40%);" action="{% url 'content:ownership' issue.series issue.issue_num 'readingtoggleread' %}" method="post">
		            	{% csrf_token %}
			        		<button type="submit" class="btn btn-success btn-sm">mark as read</button>
			        </form>
				</li>
				{% endfor %}
				<!-- </ul> -->
			</div>
		</div>
	</div>
</div>
</body>

</html>